### ISSUE TITLE
Implementar codigo python para funciones custom

### ISSUE THREAD

**Issue by princesamee** [unipeinformatica/blockly#18]
- [ ]   Blockly.Python['leer_caracter'] = function(block) 
- [ ]   Blockly.Python['avanzar_caracter'] = function(block) 
- [ ]   Blockly.Python['hay_mas_caracteres'] = function(block) 
- [ ]   Blockly.Python['leer_entrada_completa'] = function(block) 
- [ ]   Blockly.Python['obtener_caracter'] = function(block)

**Comment by gdeldago** [comment]
Listo
